"""empty message

Revision ID: 02014900f934
Revises: 
Create Date: 2024-03-07 19:41:22.435021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02014900f934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_alunos',
    sa.Column('id_aluno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('sobrenome', sa.String(length=200), nullable=False),
    sa.Column('nome_completo', sa.Text(), nullable=False),
    sa.Column('ano', sa.String(length=20), nullable=False),
    sa.Column('nivel_ensino', sa.Text(), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('status_aluno', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_aluno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabela_alunos')
    # ### end Alembic commands ###
