"""empty message

Revision ID: 06365602fc44
Revises: dc680a99c7f5
Create Date: 2024-03-07 22:05:04.338268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06365602fc44'
down_revision = 'dc680a99c7f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequencia',
    sa.Column('id_frequencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_frequencia')
    )
    op.create_table('tabela_aulas',
    sa.Column('id_aula', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao_aula', sa.String(length=100), nullable=True),
    sa.Column('data_aula', sa.Date(), nullable=True),
    sa.Column('habilidade_bncc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_aula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabela_aulas')
    op.drop_table('frequencia')
    # ### end Alembic commands ###
