"""empty message

Revision ID: 079dd262cab6
Revises: 1b84012e0a46
Create Date: 2024-03-20 22:02:26.563490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '079dd262cab6'
down_revision = '1b84012e0a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_atv', sa.Float(), nullable=True))
        batch_op.drop_column('score_atv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_atv', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('total_atv')

    # ### end Alembic commands ###
