"""empty message

Revision ID: 1b84012e0a46
Revises: e1c79c6ddfa7
Create Date: 2024-03-18 22:52:03.946790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b84012e0a46'
down_revision = 'e1c79c6ddfa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bncc_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('k_obj', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bncc_table', schema=None) as batch_op:
        batch_op.drop_column('k_obj')

    # ### end Alembic commands ###
