"""empty message

Revision ID: 212a2c1f266d
Revises: 8317d1c73ec5
Create Date: 2024-04-10 17:20:06.510422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212a2c1f266d'
down_revision = '8317d1c73ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups_table', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
