"""empty message

Revision ID: 24b7ef41a0e9
Revises: ad9fad2d49cc
Create Date: 2024-03-07 22:27:09.987646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b7ef41a0e9'
down_revision = 'ad9fad2d49cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_turma', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tabela_turmas', ['id_turma'], ['id_turma'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_alunos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_turma')

    # ### end Alembic commands ###
