"""empty message

Revision ID: 3c631cebcd19
Revises: ddd629de4ebe
Create Date: 2024-04-03 18:48:06.723759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c631cebcd19'
down_revision = 'ddd629de4ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('score_controll_table',
    sa.Column('score_controll_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score_id', sa.Integer(), nullable=True),
    sa.Column('score_now', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['score_id'], ['scores_table.score_id'], ),
    sa.PrimaryKeyConstraint('score_controll_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_controll_table')
    # ### end Alembic commands ###
