"""empty message

Revision ID: 4595fffdd429
Revises: c068b71722f0
Create Date: 2024-04-06 09:35:21.272209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4595fffdd429'
down_revision = 'c068b71722f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bncc_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'subjects_table', ['subject_id'], ['subject_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bncc_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('subject_id')

    # ### end Alembic commands ###
