"""empty message

Revision ID: 45b67ce2ecb3
Revises: 5ef2ced094ed
Create Date: 2024-03-08 22:05:42.013731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b67ce2ecb3'
down_revision = '5ef2ced094ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequencia_alunos',
    sa.Column('id_frequencia', sa.Integer(), nullable=True),
    sa.Column('id_aluno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_aluno'], ['tabela_alunos.id_aluno'], ),
    sa.ForeignKeyConstraint(['id_frequencia'], ['tabela_frequencias.id_frequencia'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frequencia_alunos')
    # ### end Alembic commands ###
