"""empty message

Revision ID: 4ff33d828962
Revises: 5362936fbcdf
Create Date: 2024-03-18 21:44:59.688715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ff33d828962'
down_revision = '5362936fbcdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bncc_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eighth_el_school', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('nineth_el_school', sa.Boolean(), nullable=True))
        batch_op.drop_column('nineth')
        batch_op.drop_column('eighth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bncc_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eighth', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nineth', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('nineth_el_school')
        batch_op.drop_column('eighth_el_school')

    # ### end Alembic commands ###
