"""empty message

Revision ID: 5362936fbcdf
Revises: ddd14ff6755a
Create Date: 2024-03-18 21:43:33.666333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5362936fbcdf'
down_revision = 'ddd14ff6755a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bncc_table',
    sa.Column('bncc_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cur_comp', sa.String(length=20), nullable=True),
    sa.Column('skill', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('first_el_school', sa.Boolean(), nullable=True),
    sa.Column('second_el_school', sa.Boolean(), nullable=True),
    sa.Column('third_el_school', sa.Boolean(), nullable=True),
    sa.Column('fourth_el_school', sa.Boolean(), nullable=True),
    sa.Column('fifth_el_school', sa.Boolean(), nullable=True),
    sa.Column('sixth_el_school', sa.Boolean(), nullable=True),
    sa.Column('seventh_el_school', sa.Boolean(), nullable=True),
    sa.Column('eighth', sa.Boolean(), nullable=True),
    sa.Column('nineth', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('bncc_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bncc_table')
    # ### end Alembic commands ###
