"""empty message

Revision ID: 5ef2ced094ed
Revises: 9e3e5a167cd3
Create Date: 2024-03-07 22:56:23.483151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef2ced094ed'
down_revision = '9e3e5a167cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_aulas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_materia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_bimestre', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_turma', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tabela_bimestres', ['id_bimestre'], ['id_bimestre'])
        batch_op.create_foreign_key(None, 'tabela_turmas', ['id_turma'], ['id_turma'])
        batch_op.create_foreign_key(None, 'tabela_materias', ['id_materia'], ['id_materia'])

    with op.batch_alter_table('tabela_frequencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_aula', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_aluno', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tabela_alunos', ['id_aluno'], ['id_aluno'])
        batch_op.create_foreign_key(None, 'tabela_aulas', ['id_aula'], ['id_aula'])

    with op.batch_alter_table('tabela_notas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_atividade', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_aluno', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tabela_atividades', ['id_atividade'], ['id_atividade'])
        batch_op.create_foreign_key(None, 'tabela_alunos', ['id_aluno'], ['id_aluno'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_notas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_aluno')
        batch_op.drop_column('id_atividade')

    with op.batch_alter_table('tabela_frequencias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_aluno')
        batch_op.drop_column('id_aula')

    with op.batch_alter_table('tabela_aulas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_turma')
        batch_op.drop_column('id_bimestre')
        batch_op.drop_column('id_materia')

    # ### end Alembic commands ###
