"""empty message

Revision ID: 6b3ad6c166ec
Revises: 97f9ec8b739a
Create Date: 2024-03-30 21:30:08.064881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b3ad6c166ec'
down_revision = '97f9ec8b739a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.drop_constraint('bim_now_table_ibfk_6', type_='foreignkey')
        batch_op.drop_column('act_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('act_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('bim_now_table_ibfk_6', 'activities_table', ['act_id'], ['act_id'])

    # ### end Alembic commands ###
