"""empty message

Revision ID: 7279a059d6fa
Revises: 212a2c1f266d
Create Date: 2024-04-10 17:22:07.350410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7279a059d6fa'
down_revision = '212a2c1f266d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_table', schema=None) as batch_op:
        batch_op.drop_column('grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', mysql.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
