"""empty message

Revision ID: 7582c240e55e
Revises: 02014900f934
Create Date: 2024-03-07 19:46:23.978022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7582c240e55e'
down_revision = '02014900f934'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabela_alunos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_alunos',
    sa.Column('id_aluno', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('sobrenome', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('nome_completo', mysql.TEXT(), nullable=False),
    sa.Column('ano', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('nivel_ensino', mysql.TEXT(), nullable=False),
    sa.Column('data_nascimento', mysql.DATETIME(), nullable=False),
    sa.Column('data_cadastro', mysql.DATETIME(), nullable=False),
    sa.Column('status_aluno', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_aluno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
