"""empty message

Revision ID: 76b7c5b67379
Revises: b1e194b7756e
Create Date: 2024-03-30 20:47:01.184663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b7c5b67379'
down_revision = 'b1e194b7756e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bim_now_table',
    sa.Column('bim_now_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('bim_total_id', sa.Integer(), nullable=True),
    sa.Column('bimester_id', sa.Integer(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('bim_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['activities_table.act_id'], ),
    sa.ForeignKeyConstraint(['bim_total_id'], ['bim_total_table.bim_total_id'], ),
    sa.ForeignKeyConstraint(['bimester_id'], ['bimesters_table.bimester_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups_table.group_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects_table.subject_id'], ),
    sa.PrimaryKeyConstraint('bim_now_id')
    )
    with op.batch_alter_table('activities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bim_now_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bim_now_table', ['bim_now_id'], ['bim_now_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bim_now_id')

    op.drop_table('bim_now_table')
    # ### end Alembic commands ###
