"""empty message

Revision ID: 815120ca93a6
Revises: 76b7c5b67379
Create Date: 2024-03-30 21:19:00.906302

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '815120ca93a6'
down_revision = '76b7c5b67379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bim_now_sum', sa.Float(), nullable=True))
        batch_op.drop_column('bim_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bim_total', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('bim_now_sum')

    # ### end Alembic commands ###
