"""empty message

Revision ID: 83d2f71551c4
Revises: 06365602fc44
Create Date: 2024-03-07 22:05:47.855050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83d2f71551c4'
down_revision = '06365602fc44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_frequencias',
    sa.Column('id_frequencia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_frequencia')
    )
    op.drop_table('frequencia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frequencia',
    sa.Column('id_frequencia', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('presente', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_frequencia'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tabela_frequencias')
    # ### end Alembic commands ###
