"""empty message

Revision ID: 97f9ec8b739a
Revises: b3a1d69a945c
Create Date: 2024-03-30 21:27:17.902566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97f9ec8b739a'
down_revision = 'b3a1d69a945c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('act_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'activities_table', ['act_id'], ['act_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('act_id')

    # ### end Alembic commands ###
