"""empty message

Revision ID: 9e3e5a167cd3
Revises: 24b7ef41a0e9
Create Date: 2024-03-07 22:36:47.112258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3e5a167cd3'
down_revision = '24b7ef41a0e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_atividades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_turma', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_materia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_bimestre', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tabela_turmas', ['id_turma'], ['id_turma'])
        batch_op.create_foreign_key(None, 'tabela_materias', ['id_materia'], ['id_materia'])
        batch_op.create_foreign_key(None, 'tabela_bimestres', ['id_bimestre'], ['id_bimestre'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_atividades', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_bimestre')
        batch_op.drop_column('id_materia')
        batch_op.drop_column('id_turma')

    # ### end Alembic commands ###
