"""empty message

Revision ID: a520a2b1e1ed
Revises: a7dc6e6df5d9
Create Date: 2024-03-07 21:03:03.131667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a520a2b1e1ed'
down_revision = 'a7dc6e6df5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_materias',
    sa.Column('id_materia', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('materia', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabela_materias')
    # ### end Alembic commands ###
