"""empty message

Revision ID: a7dc6e6df5d9
Revises: 4d5521e9cca8
Create Date: 2024-03-07 20:46:42.425839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7dc6e6df5d9'
down_revision = '4d5521e9cca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_alunos', schema=None) as batch_op:
        batch_op.alter_column('data_nascimento',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('data_cadastro',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabela_alunos', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('data_nascimento',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
