"""empty message

Revision ID: abf0011baab8
Revises: c7b857118c71
Create Date: 2024-03-22 22:04:40.284484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf0011baab8'
down_revision = 'c7b857118c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bimesters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_bim', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bimesters_table', schema=None) as batch_op:
        batch_op.drop_column('total_bim')

    # ### end Alembic commands ###
