"""empty message

Revision ID: b1e194b7756e
Revises: e550a7f8037d
Create Date: 2024-03-28 20:28:11.664702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1e194b7756e'
down_revision = 'e550a7f8037d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bim_total_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('activities_table_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bim_total_table', ['bim_total_id'], ['bim_total_id'])
        batch_op.drop_column('bimpar_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bimpar_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('activities_table_ibfk_2', 'bim_total_table', ['bimpar_id'], ['bim_total_id'])
        batch_op.drop_column('bim_total_id')

    # ### end Alembic commands ###
