"""empty message

Revision ID: b3a1d69a945c
Revises: 815120ca93a6
Create Date: 2024-03-30 21:20:27.640955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3a1d69a945c'
down_revision = '815120ca93a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.drop_constraint('bim_now_table_ibfk_1', type_='foreignkey')
        batch_op.drop_column('act_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bim_now_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('act_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('bim_now_table_ibfk_1', 'activities_table', ['act_id'], ['act_id'])

    # ### end Alembic commands ###
