"""empty message

Revision ID: b96749b99866
Revises: c6378509435d
Create Date: 2024-03-24 08:35:19.881099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96749b99866'
down_revision = 'c6378509435d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['activities_table.act_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students_table.student_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###
