"""empty message

Revision ID: c068b71722f0
Revises: 3c631cebcd19
Create Date: 2024-04-05 19:51:29.767852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c068b71722f0'
down_revision = '3c631cebcd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures_table', schema=None) as batch_op:
        batch_op.drop_column('bncc_skill')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bncc_skill', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
