"""empty message

Revision ID: c6378509435d
Revises: abf0011baab8
Create Date: 2024-03-23 09:15:02.052405

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6378509435d'
down_revision = 'abf0011baab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bimesters_table', schema=None) as batch_op:
        batch_op.drop_column('total_bim')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bimesters_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_bim', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
