"""empty message

Revision ID: dc680a99c7f5
Revises: a520a2b1e1ed
Create Date: 2024-03-07 21:14:33.205244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc680a99c7f5'
down_revision = 'a520a2b1e1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabela_notas',
    sa.Column('id_nota', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_nota')
    )
    op.create_table('tabela_turmas',
    sa.Column('id_turma', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turma', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_turma')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabela_turmas')
    op.drop_table('tabela_notas')
    # ### end Alembic commands ###
