"""empty message

Revision ID: ddd14ff6755a
Revises: 
Create Date: 2024-03-16 23:20:48.177857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd14ff6755a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bimesters_table',
    sa.Column('bimester_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bimester', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('bimester_id')
    )
    op.create_table('groups_table',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('subjects_table',
    sa.Column('subject_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('activities_table',
    sa.Column('act_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_date', sa.Date(), nullable=True),
    sa.Column('act_description', sa.String(length=100), nullable=True),
    sa.Column('score_atv', sa.Float(), nullable=True),
    sa.Column('act_status', sa.Boolean(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('bimester_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bimester_id'], ['bimesters_table.bimester_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups_table.group_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects_table.subject_id'], ),
    sa.PrimaryKeyConstraint('act_id')
    )
    op.create_table('lectures_table',
    sa.Column('lecture_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lecture_description', sa.String(length=100), nullable=True),
    sa.Column('lecture_date', sa.Date(), nullable=True),
    sa.Column('bncc_skill', sa.Text(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('bimester_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bimester_id'], ['bimesters_table.bimester_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups_table.group_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects_table.subject_id'], ),
    sa.PrimaryKeyConstraint('lecture_id')
    )
    op.create_table('students_table',
    sa.Column('student_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('date_birth', sa.Date(), nullable=False),
    sa.Column('date_registration', sa.Date(), nullable=False),
    sa.Column('student_status', sa.Boolean(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups_table.group_id'], ),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('frequencies_table',
    sa.Column('frequency_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('lecture_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures_table.lecture_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students_table.student_id'], ),
    sa.PrimaryKeyConstraint('frequency_id')
    )
    op.create_table('scores_table',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('act_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['activities_table.act_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students_table.student_id'], ),
    sa.PrimaryKeyConstraint('score_id')
    )
    op.create_table('students_frequency',
    sa.Column('frequency_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frequency_id'], ['frequencies_table.frequency_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students_table.student_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students_frequency')
    op.drop_table('scores_table')
    op.drop_table('frequencies_table')
    op.drop_table('students_table')
    op.drop_table('lectures_table')
    op.drop_table('activities_table')
    op.drop_table('subjects_table')
    op.drop_table('groups_table')
    op.drop_table('bimesters_table')
    # ### end Alembic commands ###
