"""empty message

Revision ID: ddd629de4ebe
Revises: 6b3ad6c166ec
Create Date: 2024-03-31 21:08:19.712245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddd629de4ebe'
down_revision = '6b3ad6c166ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('act_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['activities_table.act_id'], name='scores_ibfk_1'),
    sa.ForeignKeyConstraint(['student_id'], ['students_table.student_id'], name='scores_ibfk_2'),
    sa.PrimaryKeyConstraint('act_id', 'student_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
