"""empty message

Revision ID: e1c79c6ddfa7
Revises: 4ff33d828962
Create Date: 2024-03-18 21:48:04.297936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c79c6ddfa7'
down_revision = '4ff33d828962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bncc_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'bncc_table', ['bncc_id'], ['bncc_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lectures_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bncc_id')

    # ### end Alembic commands ###
